### ISSUE TITLE
Constraing staff number

### ISSUE THREAD

**Issue by moqca** [Staffjoy/chomp-decomposition#1]
There are situations where, due to spikes on demand, you end overstaffed. Is there a way to limit the number of staff that the function can use?

**Comment by philipithomas** [comment]
@moqca You could probably modify the source code. I think the main problem is the timeout - I would try extending that. Shorter shifts would help too - the narrower the shift length range, the faster the calculation. 

If you have example data, you're welcome to submit it here. Chomp was written quickly and it hasn't been maintained in a long time.
